---
- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Configure fail2ban
  ansible.builtin.include_tasks: fail2ban.yml

- name: Harden SSH
  ansible.builtin.include_tasks: ssh.yml
