# Generated by Django 5.1.4 on 2026-03-22 19:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alert_id", models.UUIDField()),
                ("rule_id", models.UUIDField(null=True)),
                ("device_id", models.CharField(max_length=64)),
                ("plant", models.CharField(max_length=64)),
                ("area", models.CharField(max_length=64)),
                ("alert_type", models.CharField(max_length=20)),
                ("severity", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("value", models.FloatField(null=True)),
                ("threshold", models.FloatField(null=True)),
                ("triggered_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(null=True)),
                ("resolved_at", models.DateTimeField(null=True)),
                ("duration_seconds", models.IntegerField()),
                ("acknowledged_by", models.CharField(blank=True, max_length=128)),
                ("resolved_by", models.CharField(blank=True, max_length=128)),
                ("resolution_notes", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alert History",
                "verbose_name_plural": "Alert History",
                "db_table": "alerts_history",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "-triggered_at"],
                        name="alerts_hist_device__39fa58_idx",
                    ),
                    models.Index(
                        fields=["area", "-triggered_at"],
                        name="alerts_hist_area_042df0_idx",
                    ),
                    models.Index(
                        fields=["severity", "-triggered_at"],
                        name="alerts_hist_severit_584f7f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "area_code",
                    models.CharField(
                        blank=True,
                        help_text="Apply to all devices in this area",
                        max_length=64,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("threshold_high", "High Threshold"),
                            ("threshold_low", "Low Threshold"),
                            ("threshold_range", "Out of Range"),
                            ("rate_of_change", "Rate of Change"),
                            ("stale_data", "Stale Data"),
                            ("quality_bad", "Bad Quality"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        blank=True,
                        help_text="Threshold value for high/low rules",
                        null=True,
                    ),
                ),
                (
                    "threshold_low",
                    models.FloatField(
                        blank=True, help_text="Low threshold for range rules", null=True
                    ),
                ),
                (
                    "threshold_high",
                    models.FloatField(
                        blank=True,
                        help_text="High threshold for range rules",
                        null=True,
                    ),
                ),
                (
                    "rate_threshold",
                    models.FloatField(
                        blank=True,
                        help_text="Rate of change threshold (units/minute)",
                        null=True,
                    ),
                ),
                (
                    "stale_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Minutes before data is considered stale",
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("notify_slack", models.BooleanField(default=True)),
                (
                    "slack_channel",
                    models.CharField(
                        blank=True,
                        default="#forgelink-alerts",
                        help_text="Slack channel for notifications",
                        max_length=64,
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="Minutes before same alert can fire again",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=128)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific device (leave blank for type/area rules)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="assets.device",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apply to all devices of this type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="assets.devicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
                "db_table": "alerts_rule",
                "ordering": ["-severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alert_type", models.CharField(max_length=20)),
                ("severity", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.CharField(blank=True, max_length=128)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=128)),
                ("notified_slack", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="assets.device",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "alerts_alert",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-triggered_at"],
                        name="alerts_aler_status_f530c6_idx",
                    ),
                    models.Index(
                        fields=["device", "-triggered_at"],
                        name="alerts_aler_device__b9616c_idx",
                    ),
                    models.Index(
                        fields=["severity", "status"],
                        name="alerts_aler_severit_12d0e1_idx",
                    ),
                ],
            },
        ),
    ]
