# Generated by Django 5.1.4 on 2026-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="notified_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="email_recipients",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated email recipients. Empty when notify_email is false. Ignored otherwise.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="notify_email",
            field=models.BooleanField(
                default=False, help_text="Dispatch an email when this rule fires"
            ),
        ),
    ]
