# Generated by Django 5.1.4 on 2026-03-22 19:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("login_count", models.IntegerField(default=0)),
                ("logout_count", models.IntegerField(default=0)),
                ("create_count", models.IntegerField(default=0)),
                ("read_count", models.IntegerField(default=0)),
                ("update_count", models.IntegerField(default=0)),
                ("delete_count", models.IntegerField(default=0)),
                ("alert_acknowledge_count", models.IntegerField(default=0)),
                ("alert_resolve_count", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(blank=True, null=True)),
                ("max_response_time_ms", models.IntegerField(blank=True, null=True)),
                ("top_resources", models.JSONField(blank=True, default=list)),
                ("top_users", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Summary",
                "verbose_name_plural": "Audit Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="User ID or email",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "role_code",
                    models.CharField(
                        blank=True,
                        help_text="User role at time of action",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("acknowledge", "Acknowledge"),
                            ("resolve", "Resolve"),
                            ("execute", "Execute"),
                            ("configure", "Configure"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        db_index=True,
                        help_text="Resource path or identifier (e.g., /api/alerts/123)",
                        max_length=255,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of resource (e.g., Alert, Device, Plant)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="Specific resource ID if applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="HTTP method (GET, POST, etc.)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="Client IP address",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Client user agent string", null=True
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="HTTP response status code",
                        null=True,
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Request duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured details about the action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "timestamp"],
                        name="audit_audit_resourc_ced1a1_idx",
                    ),
                    models.Index(
                        fields=["status_code", "timestamp"],
                        name="audit_audit_status__5c904b_idx",
                    ),
                ],
            },
        ),
    ]
