# Generated by Django 5.1.4 on 2026-03-22 19:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature Sensor"),
                            ("pressure", "Pressure Sensor"),
                            ("flow", "Flow Meter"),
                            ("level", "Level Sensor"),
                            ("vibration", "Vibration Sensor"),
                            ("current", "Current Sensor"),
                            ("voltage", "Voltage Sensor"),
                            ("speed", "Speed Sensor"),
                            ("force", "Force Sensor"),
                            ("position", "Position Sensor"),
                            ("weight", "Weight Sensor"),
                            ("humidity", "Humidity Sensor"),
                            ("gas", "Gas Concentration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("min_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("max_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                (
                    "noise_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.01,
                        help_text="Random noise as fraction of range (0.01 = 1%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "drift_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0001,
                        help_text="Value drift per second as fraction of range",
                        max_digits=8,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        default=100, help_text="Sensor response time in milliseconds"
                    ),
                ),
                (
                    "dead_band",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.5,
                        help_text="Minimum change to report (absolute value)",
                        max_digits=8,
                    ),
                ),
                (
                    "high_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "low_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "mtbf_hours",
                    models.PositiveIntegerField(
                        default=8760, help_text="Mean Time Between Failures in hours"
                    ),
                ),
                (
                    "mttr_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Mean Time To Repair in minutes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Profile",
                "verbose_name_plural": "Device Profiles",
                "ordering": ["sensor_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SimulatedPLC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plc_type",
                    models.CharField(
                        choices=[
                            ("siemens_s7", "Siemens S7-1500"),
                            ("allen_bradley", "Allen-Bradley ControlLogix"),
                            ("schneider", "Schneider Modicon"),
                            ("generic", "Generic PLC"),
                        ],
                        default="generic",
                        max_length=20,
                    ),
                ),
                (
                    "plant",
                    models.CharField(default="steel-plant-kigali", max_length=64),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("melt-shop", "Melt Shop"),
                            ("continuous-casting", "Continuous Casting"),
                            ("rolling-mill", "Rolling Mill"),
                            ("finishing", "Finishing"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "line",
                    models.CharField(
                        help_text="e.g., eaf-1, caster-1, roughing", max_length=32
                    ),
                ),
                (
                    "cell",
                    models.CharField(
                        blank=True, help_text="e.g., electrode-a, mold", max_length=32
                    ),
                ),
                (
                    "opc_namespace",
                    models.CharField(
                        blank=True, help_text="OPC-UA namespace URI", max_length=100
                    ),
                ),
                (
                    "opc_node_id_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix for OPC-UA node IDs",
                        max_length=200,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("is_simulating", models.BooleanField(default=False)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_rate_ms",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="How often to publish values (milliseconds)",
                    ),
                ),
                (
                    "publish_rate_ms",
                    models.PositiveIntegerField(
                        default=1000, help_text="MQTT publish interval (milliseconds)"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Simulated PLC",
                "verbose_name_plural": "Simulated PLCs",
                "ordering": ["area", "line", "name"],
                "unique_together": {("plant", "area", "line", "cell", "name")},
            },
        ),
        migrations.CreateModel(
            name="SimulatedDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Unique device identifier (e.g., temp-sensor-001)",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("running", "Running (Simulating)"),
                            ("fault", "Fault"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target value for simulation (sensor will trend toward this)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("bad", "Bad"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("sequence_number", models.BigIntegerField(default=0)),
                (
                    "min_value_override",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "max_value_override",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "noise_override",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "simulation_mode",
                    models.CharField(
                        choices=[
                            ("random_walk", "Random Walk"),
                            ("sine_wave", "Sine Wave"),
                            ("step", "Step Function"),
                            ("ramp", "Ramp"),
                            ("constant", "Constant"),
                            ("realistic", "Realistic (Process-based)"),
                        ],
                        default="realistic",
                        max_length=20,
                    ),
                ),
                (
                    "sine_period_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Period for sine wave simulation"
                    ),
                ),
                (
                    "ramp_rate_per_second",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Rate of change for ramp simulation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "fault_type",
                    models.CharField(
                        choices=[
                            ("none", "No Fault"),
                            ("stuck", "Stuck Value"),
                            ("drift", "Excessive Drift"),
                            ("noise", "Excessive Noise"),
                            ("spike", "Random Spikes"),
                            ("dead", "Dead Sensor"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("fault_start", models.DateTimeField(blank=True, null=True)),
                ("fault_end", models.DateTimeField(blank=True, null=True)),
                ("messages_sent", models.BigIntegerField(default=0)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("last_value_change_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="simulator.deviceprofile",
                    ),
                ),
                (
                    "plc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="simulator.simulatedplc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulated Device",
                "verbose_name_plural": "Simulated Devices",
                "ordering": ["plc", "device_id"],
                "unique_together": {("plc", "device_id")},
            },
        ),
        migrations.CreateModel(
            name="SimulationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_stop", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Auto-stop after this duration", null=True
                    ),
                ),
                (
                    "scenario",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Predefined scenario configuration",
                    ),
                ),
                ("messages_sent", models.BigIntegerField(default=0)),
                ("events_generated", models.PositiveIntegerField(default=0)),
                ("faults_injected", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sessions",
                        to="simulator.simulateddevice",
                    ),
                ),
                (
                    "plcs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Include all devices from these PLCs",
                        related_name="sessions",
                        to="simulator.simulatedplc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation Session",
                "verbose_name_plural": "Simulation Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("threshold_high", "High Threshold Exceeded"),
                            ("threshold_low", "Low Threshold Exceeded"),
                            ("critical_high", "Critical High"),
                            ("critical_low", "Critical Low"),
                            ("device_fault", "Device Fault"),
                            ("device_recovery", "Device Recovery"),
                            ("plc_offline", "PLC Offline"),
                            ("plc_online", "PLC Online"),
                            ("rate_of_change", "Abnormal Rate of Change"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_by", models.CharField(blank=True, max_length=100)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("published_to_mqtt", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="simulator.simulateddevice",
                    ),
                ),
                (
                    "plc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="simulator.simulatedplc",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="simulator.simulationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation Event",
                "verbose_name_plural": "Simulation Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-created_at"],
                        name="simulator_s_device__acc71c_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="simulator_s_severit_eca18b_idx",
                    ),
                    models.Index(
                        fields=["acknowledged", "-created_at"],
                        name="simulator_s_acknowl_b800f5_idx",
                    ),
                ],
            },
        ),
    ]
