# Generated by Django 5.1.4 on 2026-03-22 19:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Area code (e.g., melt-shop)",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Production"),
                            ("secondary", "Secondary Processing"),
                            ("finishing", "Finishing"),
                            ("utility", "Utilities"),
                            ("storage", "Storage"),
                            ("quality", "Quality Control"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0,
                        help_text="Order in production flow (1=first, 2=second, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "db_table": "assets_area",
                "ordering": ["plant", "sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Cell code (e.g., electrode-a)",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Cell",
                "verbose_name_plural": "Work Cells",
                "db_table": "assets_cell",
                "ordering": ["line", "code"],
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Type code (e.g., temperature)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "default_unit",
                    models.CharField(
                        help_text="Default unit of measurement (e.g., °C, bar, mm/s)",
                        max_length=20,
                    ),
                ),
                (
                    "typical_min",
                    models.FloatField(
                        blank=True, help_text="Typical minimum value", null=True
                    ),
                ),
                (
                    "typical_max",
                    models.FloatField(
                        blank=True, help_text="Typical maximum value", null=True
                    ),
                ),
                ("icon", models.CharField(blank=True, default="sensor", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Type",
                "verbose_name_plural": "Device Types",
                "db_table": "assets_device_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique plant code (e.g., steel-plant-kigali)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("timezone", models.CharField(default="Africa/Kigali", max_length=64)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("commissioned_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "db_table": "assets_plant",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique device ID (e.g., temp-sensor-001)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("manufacturer", models.CharField(blank=True, max_length=128)),
                ("model", models.CharField(blank=True, max_length=128)),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Override unit (uses device type default if empty)",
                        max_length=20,
                    ),
                ),
                (
                    "precision",
                    models.IntegerField(
                        default=2,
                        help_text="Decimal places for display",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "sampling_rate_ms",
                    models.IntegerField(
                        default=1000,
                        help_text="Expected sampling rate in milliseconds",
                        validators=[django.core.validators.MinValueValidator(100)],
                    ),
                ),
                ("warning_low", models.FloatField(blank=True, null=True)),
                ("warning_high", models.FloatField(blank=True, null=True)),
                ("critical_low", models.FloatField(blank=True, null=True)),
                ("critical_high", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                            ("fault", "Fault"),
                            ("calibrating", "Calibrating"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("installed_at", models.DateField(blank=True, null=True)),
                ("last_calibration", models.DateField(blank=True, null=True)),
                ("next_calibration", models.DateField(blank=True, null=True)),
                (
                    "location_notes",
                    models.TextField(
                        blank=True, help_text="Physical location description"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for filtering (e.g., ['critical', 'eaf'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="assets.cell",
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="assets.devicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "assets_device",
                "ordering": ["device_id"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Line code (e.g., eaf-1)",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "design_capacity",
                    models.FloatField(
                        blank=True,
                        help_text="Design capacity (tons/hour or units/hour)",
                        null=True,
                    ),
                ),
                (
                    "capacity_unit",
                    models.CharField(blank=True, default="tons/hour", max_length=32),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="assets.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Line",
                "verbose_name_plural": "Production Lines",
                "db_table": "assets_line",
                "ordering": ["area", "code"],
            },
        ),
        migrations.AddField(
            model_name="cell",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="assets.line",
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive Maintenance"),
                            ("corrective", "Corrective Maintenance"),
                            ("calibration", "Calibration"),
                            ("inspection", "Inspection"),
                            ("replacement", "Replacement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("performed_by", models.CharField(max_length=128)),
                ("performed_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("parts_used", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("next_scheduled", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="assets.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "db_table": "assets_maintenance_record",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddField(
            model_name="area",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="assets.plant",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="assets_devi_status_03b2ce_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type"], name="assets_devi_device__557eb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["is_active"], name="assets_devi_is_acti_a3faaa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="line",
            unique_together={("area", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="cell",
            unique_together={("line", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="area",
            unique_together={("plant", "code")},
        ),
    ]
