apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgelink-staging

resources:
  - ../../base

nameSuffix: -staging

labels:
  - pairs:
      environment: staging
    includeSelectors: true
